version: 2
jobs:
  golang:1.12:
    docker:
      - image: golang:1.12-stretch
      # - image: golang:1.12-alpine
        # environment:
        #   GO111MODULE: "ON"
        #   CGO_ENABLED=0
        #   GOOS=linux
        #   GOARCH=amd64

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    # working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      # - run: apk update && apk upgrade && apk add --no-cache git make
      - run: echo "pwd=$(pwd)"
      - run: go mod download
      - run: go build ./...
      # - run: go test -timeout 5m ./...
      # - run: go test -timeout 5m -race ./...

  golang:1.11:
    docker:
      - image: golang:1.11-stretch
      # - image: golang:1.11-alpine
        # environment:
        #   GO111MODULE: "ON"
        #   CGO_ENABLED=0
        #   GOOS=linux
        #   GOARCH=amd64

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    # working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: echo "pwd=$(pwd)"
      - run: go mod download
      - run: go build ./...
      # - run: go test -timeout 5m ./...
      # - run: go test -timeout 5m -race ./...

workflows:
  version: 2
  build:
    jobs:
      - golang:1.12
      - golang:1.11
